import Login from './Login'
import Delegate from './Delegate'
import PasswordChange from './PasswordChange'
import Home from './Home'
import DashboardClaimed from './DashboardClaimed'
import DashboardRecommended from './DashboardRecommended'
import DashboardUnclaimed from './DashboardUnclaimed'
import DashboardOld from './DashboardOld'
import FormFiction from './FormFiction'
import FormPoetry from './FormPoetry'
import FormNonfiction from './FormNonfiction'
import Verarbeiten from './Verarbeiten'
import Error from './Error'
import Submitted from './Submitted'
import PasswordChangeSuccess from './PasswordChangeSuccess'
import PrivateRoute from './PrivateRoute'
export { Home, Login, Delegate, PasswordChange, DashboardClaimed, DashboardRecommended, DashboardUnclaimed, DashboardOld, FormFiction, FormPoetry, FormNonfiction, Verarbeiten, Submitted, PasswordChangeSuccess, Error, PrivateRoute }
