import Login from './Login'
import AddReader from './AddReader'
import PasswordChange from './PasswordChange'
import Home from './Home'
import DashboardAll from './DashboardAll'
import FormFiction from './FormFiction'
import FormPoetry from './FormPoetry'
import FormNonfiction from './FormNonfiction'
import Verarbeiten from './Verarbeiten'
import Error from './Error'
import Submitted from './Submitted'
import PasswordChangeSuccess from './PasswordChangeSuccess'
import PrivateRoute from './PrivateRoute'
export { Home, Login, AddReader, PasswordChange, DashboardAll, FormFiction, FormPoetry, FormNonfiction, Verarbeiten, Submitted, PasswordChangeSuccess, Error, PrivateRoute }
