import Login from './Login'
import Delegate from './Delegate'
import Home from './Home'
import Dashboard from './Dashboard'
import Form from './Form'
import Verarbeiten from './Verarbeiten'
import Error from './Error'
import Submitted from './Submitted'
import PrivateRoute from './PrivateRoute'
export { Home, Login, Delegate, Dashboard, Form, Verarbeiten, Submitted, Error, PrivateRoute }
