//////// ESTABLISHES GLOBAL SET OF VALUES THAT COMPONENTS USE WITH PASSING EACH INDIVIDUALLY DOWN THE LINE. ////////

export const SET_LOADING = 'SET_LOADING'

export const DELEGATE_SUCCESS = 'DELEGATE_SUCCESS'
export const DELEGATE_ERROR = 'DELEGATE_ERROR'
export const LOGIN_READER = 'LOGIN_READER'
export const LOGOUT_READER = 'LOGOUT_READER'
export const FETCH_SUBMISSIONS_SUCCESS = 'FETCH_SUBMISSIONS_SUCCESS'
export const FETCH_SUBMISSIONS_ERROR = 'FETCH_SUBMISSIONS_ERROR'
export const CREATE_SUBMISSION_SUCCESS = 'CREATE_SUBMISSION_SUCCESS'
export const CREATE_SUBMISSION_ERROR = 'CREATE_SUBMISSION_ERROR'
export const DELETE_SUBMISSION_ERROR = 'DELETE_SUBMISSION_ERROR'
export const FETCH_SINGLE_SUBMISSION_SUCCESS = 'FETCH_SINGLE_SUBMISSION_SUCCESS'
export const FETCH_SINGLE_SUBMISSION_ERROR = 'FETCH_SINGLE_SUBMISSION_ERROR'
export const DOWNLOAD_SUBMISSION_SUCCESS = 'DOWNLOAD_SUBMISSION_SUCCESS'
export const DOWNLOAD_SUBMISSION_ERROR = 'DOWNLOAD_SUBMISSION_ERROR'
export const VERARBEITEN_SUBMISSION_SUCCESS = 'VERARBEITEN_SUBMISSION_SUCCESS'
export const VERARBEITEN_SUBMISSION_ERROR = 'VERARBEITEN_SUBMISSION_ERROR'